# سیمرغ‌اواس — صفحهٔ ورود فارسی
[Greeter]
background=/usr/share/backgrounds/simorgh/wallpaper-simorgh-dark.png
logo=/usr/share/pixmaps/simorgh.png
draw-user-backgrounds=false
draw-grid=false
show-hostname=false
theme-name=Orchis-Dark-Compact
icon-theme-name=Papirus-Dark
cursor-theme-name=Breeze
font-name=Vazirmatn 11
xft-antialias=1
indicators=~language;~session;~power
