# سیمرغ‌اواس — تنظیمات سراسری XSettings برای هماهنگی GTK/Qt
Net/ThemeName "Orchis-Dark-Compact"
Net/IconThemeName "Papirus-Dark"
Gtk/FontName "Vazirmatn 11"
Gtk/CursorThemeName "Breeze"
Xft/Antialias 1
Xft/Hinting 1
Xft/RGBA "rgb"
Net/EnableAnimations 1
