# سیمرغ‌اواس — برنامه‌های شروع نشست
exec-once = hyprpaper
exec-once = waybar
exec-once = mako
exec-once = hypridle
exec-once = hyprpolkitagent
exec-once = nm-applet --indicator
exec-once = fcitx5 -d --replace
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = xsettingsd -c /etc/xsettingsd/simorgh.conf
exec-once = /usr/share/simorgh/bin/simorgh-firstboot
exec-once = gammastep
