# سیمرغ‌اواس — پارتیشن‌بندی
---
efiSystemPartition: "/boot/efi"
swapPartition: ""
enableLuksAutomatedPartitioning: true
initialPartitioningChoice: erase
allowManualPartitioning: true
alwaysCreateSwap: false
defaultFileSystemType: "ext4"
requiredStorage: 8.0
