# سیمرغ‌اواس — کاربر و میزبان
---
defaultUserHost:
  user: simorgh
  host: simorgh
  reusePassword: true
  autologin: true
setHostname: true
writeHostsFile: true
defaultGroups: [users, sudo, audio, video, netdev, plugdev]
sudoersGroup: sudo
doReusePassword: true
allowWeakPasswords: true
allowWeakPasswordsDefault: false
autologinGroup: autologin
