[Appearance]
custom_palette=false
icon_theme=Papirus-Dark
standard_dialogs=gtk3
style=Fusion

[Fonts]
fixed="Vazirmatn,11,-1,5,50,0,0,0,0,0"
general="Vazirmatn,11,-1,5,50,0,0,0,0,0"

[Settings]
activate_item_on_single_click=1
buttonbox_layout=3
dialog_buttons_have_icons=1
gui_effects=@Invalid()
keyboard_scheme=2
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3
